# Generated by Django 5.2.9 on 2025-12-30 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.O')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Username')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Dizimnen ótken waqtı')),
            ],
            options={
                'verbose_name': 'Bot paydalanıwshısı',
                'verbose_name_plural': 'Bot paydalanıwshıları',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Soraw teksti')),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/', verbose_name='Soraw súwreti')),
                ('option_a', models.CharField(max_length=255, verbose_name='A variantı')),
                ('option_b', models.CharField(max_length=255, verbose_name='B variantı')),
                ('option_c', models.CharField(max_length=255, verbose_name='C variantı')),
                ('option_d', models.CharField(max_length=255, verbose_name='D variantı')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, verbose_name='Durıs juwap')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Soraw',
                'verbose_name_plural': 'Sorawlar',
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Toplanǵan ball')),
                ('total_questions', models.IntegerField(default=10, verbose_name='Ulıwma sorawlar sanı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tapsırılǵan waqıt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='bot_app.botuser', verbose_name='Oqıwshı')),
            ],
            options={
                'verbose_name': 'Test nátiyjesi',
                'verbose_name_plural': 'Test nátiyjeleri',
            },
        ),
        migrations.CreateModel(
            name='AttemptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1, verbose_name='Oqıwshı juvabı')),
                ('is_correct', models.BooleanField(verbose_name='Durıs pa?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_app.question', verbose_name='Soraw')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bot_app.testattempt', verbose_name='Test')),
            ],
        ),
    ]
