# Generated by Django 5.2.9 on 2026-01-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='User ID')),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('data', models.JSONField(default=dict, verbose_name='FSM Data')),
            ],
        ),
    ]
