# Generated by Django 5.2.9 on 2026-01-04 11:27

import bot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_app', '0002_botstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=bot_app.models.get_file_path, verbose_name='Soraw súwreti'),
        ),
    ]
